"""add perfil_investidor e perfil_respostas ao user

Revision ID: 76bc5053cb4b
Revises: 0ecd2f2fc03d
Create Date: 2025-07-10 09:56:19.358504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bc5053cb4b'
down_revision = '0ecd2f2fc03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_investidor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('perfil_respostas', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('perfil_respostas')
        batch_op.drop_column('perfil_investidor')

    # ### end Alembic commands ###
