version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agente-investidor-frontend
    ports:
      - "5000:5000"
    networks:
      - agente-network
    restart: unless-stopped

networks:
  agente-network:
    external: true 