global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'agente-investidor'
    environment: 'development'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics
    scrape_interval: 15s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Data Service
  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:8002']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Methodology Service
  - job_name: 'methodology-service'
    static_configs:
      - targets: ['methodology-service:8003']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Analysis Service
  - job_name: 'analysis-service'
    static_configs:
      - targets: ['analysis-service:8004']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s

  # Nginx metrics (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics
    scrape_interval: 15s

  # Kafka metrics (if JMX exporter is configured)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']
    metrics_path: /metrics
    scrape_interval: 30s

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: /metrics
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: 
        - 'auth-service:8001'
        - 'data-service:8002'
        - 'methodology-service:8003'
        - 'analysis-service:8004'
    metrics_path: /business-metrics
    scrape_interval: 60s
    honor_labels: true

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"

