cluster.name: "agente-investidor-logs"
node.name: "elasticsearch-node-1"

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery settings
discovery.type: single-node
cluster.initial_master_nodes: ["elasticsearch-node-1"]

# Security settings
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Memory settings
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 10%

# Index settings
action.auto_create_index: true
action.destructive_requires_name: true

# Logging
logger.level: INFO
logger.org.elasticsearch.discovery: DEBUG

# Index lifecycle management
xpack.ilm.enabled: true

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# Performance tuning
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 20%

# Index templates for application logs
index.number_of_shards: 1
index.number_of_replicas: 0
index.refresh_interval: 5s

# Disk usage thresholds
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

