global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@agenteinvestidor.com'
  smtp_auth_username: 'alertmanager@agenteinvestidor.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      repeat_interval: 12h

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'luiz.gustavo@agenteinvestidor.com'
        subject: '🚨 CRÍTICO: {{ .GroupLabels.alertname }} - Agente Investidor'
        body: |
          🚨 **ALERTA CRÍTICO** 🚨
          
          **Serviço:** {{ .GroupLabels.service }}
          **Ambiente:** {{ .GroupLabels.environment }}
          **Severidade:** {{ .GroupLabels.severity }}
          
          **Alertas Ativos:**
          {{ range .Alerts }}
          - **{{ .Annotations.summary }}**
            {{ .Annotations.description }}
            Iniciado em: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
          
          **Ação Requerida:** Investigação imediata necessária!
          
          Dashboard: http://grafana.agenteinvestidor.com
          Logs: http://kibana.agenteinvestidor.com
        html: |
          <h2 style="color: red;">🚨 ALERTA CRÍTICO 🚨</h2>
          <p><strong>Serviço:</strong> {{ .GroupLabels.service }}</p>
          <p><strong>Ambiente:</strong> {{ .GroupLabels.environment }}</p>
          <p><strong>Severidade:</strong> {{ .GroupLabels.severity }}</p>
          
          <h3>Alertas Ativos:</h3>
          <ul>
          {{ range .Alerts }}
          <li>
            <strong>{{ .Annotations.summary }}</strong><br>
            {{ .Annotations.description }}<br>
            <em>Iniciado em: {{ .StartsAt.Format "2006-01-02 15:04:05" }}</em>
          </li>
          {{ end }}
          </ul>
          
          <p><strong>Ação Requerida:</strong> Investigação imediata necessária!</p>
          
          <p>
            <a href="http://grafana.agenteinvestidor.com">Dashboard</a> |
            <a href="http://kibana.agenteinvestidor.com">Logs</a>
          </p>
    
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: '🚨 CRÍTICO: {{ .GroupLabels.alertname }}'
        text: |
          **Serviço:** {{ .GroupLabels.service }}
          **Ambiente:** {{ .GroupLabels.environment }}
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        color: 'danger'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'luiz.gustavo@agenteinvestidor.com'
        subject: '⚠️ ATENÇÃO: {{ .GroupLabels.alertname }} - Agente Investidor'
        body: |
          ⚠️ **ALERTA DE ATENÇÃO** ⚠️
          
          **Serviço:** {{ .GroupLabels.service }}
          **Ambiente:** {{ .GroupLabels.environment }}
          **Severidade:** {{ .GroupLabels.severity }}
          
          **Alertas Ativos:**
          {{ range .Alerts }}
          - **{{ .Annotations.summary }}**
            {{ .Annotations.description }}
            Iniciado em: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
          
          **Ação Recomendada:** Monitoramento e investigação quando possível.
          
          Dashboard: http://grafana.agenteinvestidor.com
    
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-warning'
        title: '⚠️ ATENÇÃO: {{ .GroupLabels.alertname }}'
        text: |
          **Serviço:** {{ .GroupLabels.service }}
          **Ambiente:** {{ .GroupLabels.environment }}
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        color: 'warning'
        send_resolved: true

  - name: 'info-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-info'
        title: 'ℹ️ INFO: {{ .GroupLabels.alertname }}'
        text: |
          **Serviço:** {{ .GroupLabels.service }}
          **Ambiente:** {{ .GroupLabels.environment }}
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        color: 'good'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
  
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'cluster', 'service']

templates:
  - '/etc/alertmanager/templates/*.tmpl'

